version: '3.8'
services:
  web:
    image: backend01/image
    build: .
    volumes:
    - .:/code
    ports:
    - "1234:1234"
    environment:
      - DB_HOST=postgres
      - DB_NAME=mydb
      - DB_USER=myuser
      - DB_PASS=mypass
    depends_on:
    - postgres
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypass
    ports:
      - "5433:5432"