# Generated by Django 4.0.3 on 2022-04-06 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecommerce_link', models.URLField(max_length=500, verbose_name='Ecommerce link')),
                ('title', models.CharField(max_length=300, verbose_name='Review title')),
                ('text', models.TextField(max_length=3000, verbose_name='Review text')),
                ('star_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Stars count')),
                ('author_email', models.EmailField(max_length=254, verbose_name='Reviews author email')),
                ('domain_name', models.CharField(max_length=100, verbose_name='Domain name')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'reviews',
            },
        ),
    ]
